package de.hpi3d.gamepgrog.trap.ui;

import android.app.Activity;
import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.TextView;

import java.util.List;

import androidx.recyclerview.widget.RecyclerView;
import de.hpi3d.gamepgrog.trap.R;
import de.hpi3d.gamepgrog.trap.datatypes.Displayable;
import de.hpi3d.gamepgrog.trap.tasks.Task;

/**
 * RecyclerViewAdapter for our list of displayables, right now only
 * tasks.
 * <p>
 * Is used by DisplayableListFragment to populate its displayable list.
 * <p>
 * Pretty much 100% UI boilerplate, mostly autogenerated.
 * For details check out https://developer.android.com/guide/topics/ui/layout/recyclerview,
 * and read docs on how android handles ViewAdapters.
 */
public class DisplayableRecyclerViewAdapter extends RecyclerView.Adapter<DisplayableRecyclerViewAdapter.ViewHolder> {

    private final List<Displayable> displayableList;
    private Activity activity;

    public DisplayableRecyclerViewAdapter(List<Displayable> items, Activity activity) {
        displayableList = items;
        this.activity = activity;
    }


    @Override
    public ViewHolder onCreateViewHolder(ViewGroup parent, int viewType) {
        View view = LayoutInflater.from(parent.getContext())
                .inflate(R.layout.fragment_displayable, parent, false);
        return new ViewHolder(view);
    }

    @Override
    public void onBindViewHolder(final ViewHolder holder, int position) {
        holder.displayable = displayableList.get(position);
        Displayable correspondingDisplayable = displayableList.get(position);
        holder.displayableTextView.setText(correspondingDisplayable.getDisplayString());

        if (correspondingDisplayable instanceof Task && ((Task) correspondingDisplayable).getFinished()) {
            holder.displayableTextView.setEnabled(false);
        }
    }

    @Override
    public int getItemCount() {
        return displayableList.size();
    }

    public class ViewHolder extends RecyclerView.ViewHolder {
        public final View mView;
        public final TextView displayableTextView;
        public Displayable displayable;

        public ViewHolder(View view) {
            super(view);
            mView = view;
            displayableTextView = view.findViewById(R.id.content);
            displayableTextView.setOnClickListener(v -> {
                if (displayable instanceof Task) {
                    ((Task) displayable).execute(activity).then(
                            () -> this.displayableTextView.setEnabled(
                                    !((Task) displayable).getFinished()
                            ));
                }
            });
        }

        @Override
        public String toString() {
            return super.toString() + " '" + displayableTextView.getText() + "'";
        }
    }
}
